namespace DimonSmart.DbSketch.Core.Rendering;

public static class MarkdownDiagramWrapper
{
    public static string Wrap(string diagramText, string fenceLanguage, string title)
    {
        if (string.IsNullOrWhiteSpace(fenceLanguage))
        {
            throw new ArgumentException("Markdown fence language is required.", nameof(fenceLanguage));
        }

        return $"# {title}{Environment.NewLine}{Environment.NewLine}Generated by DbSketch.{Environment.NewLine}{Environment.NewLine}```{fenceLanguage}{Environment.NewLine}{diagramText}```{Environment.NewLine}";
    }
}
