namespace DimonSmart.DbSketch.Core.Rendering;

public static class MarkdownDiagramWrapper
{
    public static string Wrap(string diagramText, DiagramFormat format, string title)
    {
        var language = format switch
        {
            DiagramFormat.Dot => "dot",
            DiagramFormat.Mermaid => "mermaid",
            _ => throw new ArgumentOutOfRangeException(nameof(format), format, null)
        };

        return $"# {title}{Environment.NewLine}{Environment.NewLine}Generated by DbSketch.{Environment.NewLine}{Environment.NewLine}```{language}{Environment.NewLine}{diagramText}```{Environment.NewLine}";
    }
}
