using DimonSmart.DbSketch.Core.Config;
using DimonSmart.DbSketch.Core.Rendering;
using DimonSmart.DbSketch.Core.Schema;

namespace DimonSmart.DbSketch.Cli;

public sealed record ResolvedGenerateOptions(
    string Provider,
    string ConnectionString,
    string OutputPath,
    DiagramFormat DiagramRenderer,
    OutputFormat Output,
    bool Verbose,
    bool Quiet,
    bool NoProgress,
    bool DryRun,
    SchemaFilterOptions Filter,
    DiagramRenderOptions Diagram,
    bool ReadComments,
    int? CommandTimeoutSeconds,
    CommentOverridesConfig CommentOverrides);

public static class GenerateOptionsResolver
{
    public static ResolvedGenerateOptions Resolve(DbSketchConfig config, CliOptions cli)
    {
        var provider = NormalizeProvider(cli.Provider ?? config.Provider);
        var connectionString = cli.ConnectionString ?? config.ConnectionString;
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            throw new CliException("Missing connection string.");
        }

        var diagramRenderer = DiagramRendererParser.Parse(cli.Renderer ?? config.Diagram.Renderer);
        var outputFormat = OutputContainerFormatParser.Parse(cli.Format ?? config.Output.Format);
        var direction = DiagramDirectionParser.Parse(config.Diagram.Direction);
        var diagramTitle = string.IsNullOrWhiteSpace(config.Diagram.Title) ? "Database schema" : config.Diagram.Title;
        ValidateComments(config);
        ValidateDatabase(config);
        var markdownOptions = outputFormat == OutputContainerFormat.Markdown
            ? new MarkdownRenderOptions(
                GetMarkdownFenceLanguage(config.Output.Markdown.FenceLanguage, diagramRenderer),
                config.Output.Markdown.Header ?? $"# {diagramTitle}{Environment.NewLine}{Environment.NewLine}Generated by DbSketch.",
                config.Output.Markdown.Footer)
            : null;

        return new ResolvedGenerateOptions(
            provider,
            connectionString,
            cli.OutputPath ?? config.Output.Path ?? GetDefaultOutputPath(diagramRenderer, outputFormat),
            diagramRenderer,
            new OutputFormat(outputFormat, markdownOptions),
            cli.Verbose,
            cli.Quiet,
            cli.NoProgress,
            cli.DryRun,
            new SchemaFilterOptions(config.Include.Tables, config.Exclude.Tables),
            new DiagramRenderOptions(
                diagramTitle,
                direction,
                config.Diagram.Compact,
                new DiagramShowOptions(config.Diagram.Show.SchemaName, config.Diagram.Show.ColumnTypes, config.Diagram.Show.Nullability, config.Diagram.Show.PrimaryKeys, config.Diagram.Show.ForeignKeys, config.Diagram.Show.TableComments, config.Diagram.Show.ColumnComments),
                new MermaidRenderOptions(config.Diagram.Mermaid.EmitDirection),
                new DiagramCommentRenderOptions(config.Diagram.Comments.MaxLength)),
            config.Comments.Enabled,
            config.Database.CommandTimeoutSeconds,
            config.Comments.Overrides);
    }

    private static void ValidateComments(DbSketchConfig config)
    {
        if (config.Diagram.Comments.MaxLength <= 0)
        {
            throw new CliException("diagram.comments.maxLength must be greater than zero.");
        }

        var tableOverrides = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var tableOverride in config.Comments.Overrides.Tables)
        {
            if (string.IsNullOrWhiteSpace(tableOverride.Schema))
            {
                throw new CliException("comments.overrides.tables[].schema is required.");
            }

            if (string.IsNullOrWhiteSpace(tableOverride.Name))
            {
                throw new CliException("comments.overrides.tables[].name is required.");
            }

            var key = $"{tableOverride.Schema.Trim()}.{tableOverride.Name.Trim()}";
            if (!tableOverrides.Add(key))
            {
                throw new CliException($"Duplicate comment override for table '{key}'.");
            }
        }
    }

    private static void ValidateDatabase(DbSketchConfig config)
    {
        if (config.Database.CommandTimeoutSeconds is <= 0)
        {
            throw new CliException("database.commandTimeoutSeconds must be greater than zero.");
        }
    }

    private static string GetDefaultOutputPath(DiagramFormat renderer, OutputContainerFormat outputFormat) =>
        outputFormat switch
        {
            OutputContainerFormat.Markdown => "dbsketch.md",
            OutputContainerFormat.Raw when renderer == DiagramFormat.Dot => "dbsketch.dot",
            OutputContainerFormat.Raw when renderer == DiagramFormat.Mermaid => "dbsketch.mmd",
            _ => throw new ArgumentOutOfRangeException(nameof(outputFormat), outputFormat, null)
        };

    private static string GetMarkdownFenceLanguage(string? configuredLanguage, DiagramFormat renderer)
    {
        if (!string.IsNullOrWhiteSpace(configuredLanguage))
        {
            return configuredLanguage;
        }

        return renderer switch
        {
            DiagramFormat.Dot => "dot",
            DiagramFormat.Mermaid => "mermaid",
            _ => throw new ArgumentOutOfRangeException(nameof(renderer), renderer, null)
        };
    }

    public static string NormalizeProvider(string? provider)
    {
        if (string.IsNullOrWhiteSpace(provider))
        {
            throw new CliException("Missing provider.");
        }

        return provider.Trim().ToLowerInvariant() switch
        {
            "mssql" => "sqlserver",
            "sqlserver" => "sqlserver",
            "postgresql" => "postgres",
            "postgres" => "postgres",
            "mysql" => "mysql",
            var value => throw new CliException($"Unknown provider '{value}'. Supported values: sqlserver, postgres, mysql.")
        };
    }
}
