using System.Text.RegularExpressions;
using DimonSmart.DbSketch.Core.Config;
using DimonSmart.DbSketch.Core.Rendering;
using DimonSmart.DbSketch.Core.Schema;

namespace DimonSmart.DbSketch.Cli;

public sealed record ResolvedGenerateOptions(
    string Provider,
    string ConnectionString,
    bool Verbose,
    bool Quiet,
    bool NoProgress,
    bool DryRun,
    bool ReadComments,
    int? CommandTimeoutSeconds,
    CommentOverridesConfig CommentOverrides,
    IReadOnlyList<ResolvedDiagramTarget> Diagrams);

public sealed record ResolvedDiagramTarget(
    string Name,
    string OutputPath,
    DiagramFormat DiagramRenderer,
    OutputFormat Output,
    SchemaFilterOptions Filter,
    DiagramRenderOptions Diagram);

public static partial class GenerateOptionsResolver
{
    public static ResolvedGenerateOptions Resolve(DbSketchConfig config, CliOptions cli)
    {
        if (string.IsNullOrWhiteSpace(cli.ConfigPath))
        {
            throw new CliException("--config is required.");
        }

        var provider = NormalizeProvider(config.Provider);
        if (string.IsNullOrWhiteSpace(config.ConnectionString))
        {
            throw new CliException("connectionString is required.");
        }

        ValidateDatabase(config);
        ValidateComments(config);
        ValidateDiagrams(config);

        var diagrams = ResolveDiagrams(config, cli.DiagramName);

        return new ResolvedGenerateOptions(
            provider,
            config.ConnectionString,
            cli.Verbose,
            cli.Quiet,
            cli.NoProgress,
            cli.DryRun,
            config.Comments.Enabled,
            config.Database.CommandTimeoutSeconds,
            config.Comments.Overrides,
            diagrams);
    }

    private static IReadOnlyList<ResolvedDiagramTarget> ResolveDiagrams(DbSketchConfig config, string? selectedDiagramName)
    {
        var sourceDiagrams = config.Diagrams;
        if (!string.IsNullOrWhiteSpace(selectedDiagramName))
        {
            var selected = sourceDiagrams.FirstOrDefault(diagram => string.Equals(diagram.Name, selectedDiagramName, StringComparison.OrdinalIgnoreCase));
            if (selected is null)
            {
                throw new CliException($"Diagram '{selectedDiagramName}' was not found. Available diagrams: {string.Join(", ", sourceDiagrams.Select(diagram => diagram.Name))}.");
            }

            sourceDiagrams = [selected];
        }

        return sourceDiagrams.Select(diagram => ResolveDiagram(config.Defaults, diagram)).ToArray();
    }

    private static ResolvedDiagramTarget ResolveDiagram(DefaultsConfig defaults, DiagramTargetConfig target)
    {
        var diagramRenderer = DiagramRendererParser.Parse(target.Diagram?.Renderer ?? defaults.Diagram.Renderer);
        var outputFormat = OutputContainerFormatParser.Parse(target.Output?.Format ?? defaults.Output.Format);
        var direction = DiagramDirectionParser.Parse(target.Diagram?.Direction ?? defaults.Diagram.Direction);
        var style = ParseStyle(target.Diagram?.Style ?? defaults.Diagram.Style, target.Diagram?.Style is null ? "defaults.diagram.style" : $"diagrams['{target.Name}'].diagram.style");
        var title = string.IsNullOrWhiteSpace(target.Title)
            ? defaults.Diagram.Title ?? "Database schema"
            : target.Title;

        var commentMaxLength = target.Diagram?.Comments?.MaxLength ?? defaults.Diagram.Comments.MaxLength;
        ValidateCommentMaxLength(commentMaxLength, $"diagrams['{target.Name}'].diagram.comments.maxLength");
        var columnLayout = target.Diagram?.ColumnLayout ?? defaults.Diagram.ColumnLayout;
        var tableHeaderLayout = target.Diagram?.TableHeaderLayout ?? defaults.Diagram.TableHeaderLayout;
        ValidateLayout(columnLayout, ColumnLayoutFormatter.SupportedTokens, GetLayoutConfigPath(target, target.Diagram?.ColumnLayout, "columnLayout"));
        ValidateLayout(tableHeaderLayout, TableHeaderLayoutFormatter.SupportedTokens, GetLayoutConfigPath(target, target.Diagram?.TableHeaderLayout, "tableHeaderLayout"));
        var dot = ResolveDotOptions(defaults.Diagram.Dot, target.Diagram?.Dot, style, target);

        var markdownOptions = outputFormat == OutputContainerFormat.Markdown
            ? new MarkdownRenderOptions(
                GetMarkdownFenceLanguage(target.Output?.Markdown?.FenceLanguage ?? defaults.Output.Markdown.FenceLanguage, diagramRenderer),
                target.Output?.Markdown?.Header ?? defaults.Output.Markdown.Header ?? $"# {title}{Environment.NewLine}{Environment.NewLine}Generated by DbSketch.",
                target.Output?.Markdown?.Footer ?? defaults.Output.Markdown.Footer)
            : null;

        return new ResolvedDiagramTarget(
            target.Name!,
            target.Output!.Path!,
            diagramRenderer,
            new OutputFormat(outputFormat, markdownOptions),
            new SchemaFilterOptions(target.Include.Tables, target.Exclude.Tables),
            new DiagramRenderOptions(
                title,
                direction,
                style,
                target.Diagram?.Compact ?? defaults.Diagram.Compact,
                new DiagramLayoutOptions(columnLayout, tableHeaderLayout),
                ResolveShowOptions(defaults.Diagram.Show, target.Diagram?.Show),
                new MermaidRenderOptions(target.Diagram?.Mermaid?.EmitDirection ?? defaults.Diagram.Mermaid.EmitDirection),
                new DiagramCommentRenderOptions(commentMaxLength),
                dot));
    }

    private static DiagramStyle ParseStyle(string? style, string path) =>
        style?.Trim().ToLowerInvariant() switch
        {
            "classic" => DiagramStyle.Classic,
            "readable" => DiagramStyle.Readable,
            "compact" => DiagramStyle.Compact,
            "soft" => DiagramStyle.Soft,
            "blueprint" => DiagramStyle.Blueprint,
            "contrast" => DiagramStyle.Contrast,
            var value => throw new CliException($"{path} must be one of: classic, readable, compact, soft, blueprint, contrast.")
        };

    private static string GetLayoutConfigPath(DiagramTargetConfig target, string? overrideValue, string propertyName) =>
        overrideValue is null
            ? $"defaults.diagram.{propertyName}"
            : $"diagrams['{target.Name}'].diagram.{propertyName}";

    private static void ValidateLayout(string? layout, IReadOnlySet<string> supportedTokens, string configPath)
    {
        if (layout is null)
        {
            return;
        }

        try
        {
            LayoutTemplateParser.Parse(layout, supportedTokens, configPath);
        }
        catch (LayoutTemplateException exception)
        {
            throw new CliException(exception.Message);
        }
    }

    private static DiagramShowOptions ResolveShowOptions(DiagramShowConfig defaults, DiagramShowOverrideConfig? overrides) =>
        new(
            overrides?.SchemaName ?? defaults.SchemaName,
            overrides?.ColumnTypes ?? defaults.ColumnTypes,
            overrides?.Nullability ?? defaults.Nullability,
            overrides?.PrimaryKeys ?? defaults.PrimaryKeys,
            overrides?.ForeignKeys ?? defaults.ForeignKeys,
            overrides?.ForeignKeyLabels ?? defaults.ForeignKeyLabels,
            overrides?.SelfReferencingForeignKeys ?? defaults.SelfReferencingForeignKeys,
            overrides?.TableComments ?? defaults.TableComments,
            overrides?.ColumnComments ?? defaults.ColumnComments);

    private static GraphvizDotRenderOptions ResolveDotOptions(
        DotConfig defaults,
        DotOverrideConfig? overrides,
        DiagramStyle style,
        DiagramTargetConfig target)
    {
        var preset = GetDotPreset(style);
        var graph = new GraphvizDotGraphRenderOptions(
            overrides?.Graph?.FontName ?? defaults.Graph.FontName ?? preset.Graph.FontName,
            overrides?.Graph?.FontSize ?? defaults.Graph.FontSize ?? preset.Graph.FontSize,
            overrides?.Graph?.Nodesep ?? defaults.Graph.Nodesep ?? preset.Graph.Nodesep,
            overrides?.Graph?.Ranksep ?? defaults.Graph.Ranksep ?? preset.Graph.Ranksep,
            overrides?.Graph?.BackgroundColor ?? defaults.Graph.BackgroundColor ?? preset.Graph.BackgroundColor);
        var node = new GraphvizDotNodeRenderOptions(
            overrides?.Node?.FontName ?? defaults.Node.FontName ?? preset.Node.FontName,
            overrides?.Node?.FontSize ?? defaults.Node.FontSize ?? preset.Node.FontSize);
        var edge = new GraphvizDotEdgeRenderOptions(
            overrides?.Edge?.FontName ?? defaults.Edge.FontName ?? preset.Edge.FontName,
            overrides?.Edge?.FontSize ?? defaults.Edge.FontSize ?? preset.Edge.FontSize,
            overrides?.Edge?.Color ?? defaults.Edge.Color ?? preset.Edge.Color,
            overrides?.Edge?.PenWidth ?? defaults.Edge.PenWidth ?? preset.Edge.PenWidth,
            overrides?.Edge?.ArrowSize ?? defaults.Edge.ArrowSize ?? preset.Edge.ArrowSize);
        var table = new GraphvizDotTableRenderOptions(
            overrides?.Table?.BorderColor ?? defaults.Table.BorderColor ?? preset.Table.BorderColor,
            overrides?.Table?.HeaderBackground ?? defaults.Table.HeaderBackground ?? preset.Table.HeaderBackground,
            overrides?.Table?.CellPadding ?? defaults.Table.CellPadding ?? preset.Table.CellPadding);

        var basePath = overrides is null ? "defaults.diagram.dot" : $"diagrams['{target.Name}'].diagram.dot";
        ValidateFont(graph.FontName, $"{basePath}.graph.fontName");
        ValidateFont(node.FontName, $"{basePath}.node.fontName");
        ValidateFont(edge.FontName, $"{basePath}.edge.fontName");
        ValidateFontSize(graph.FontSize, $"{basePath}.graph.fontSize", 6, 72);
        ValidateFontSize(node.FontSize, $"{basePath}.node.fontSize", 6, 72);
        ValidateFontSize(edge.FontSize, $"{basePath}.edge.fontSize", 6, 72);
        ValidateColor(graph.BackgroundColor, $"{basePath}.graph.backgroundColor");
        ValidateColor(edge.Color, $"{basePath}.edge.color");
        ValidateColor(table.BorderColor, $"{basePath}.table.borderColor");
        ValidateColor(table.HeaderBackground, $"{basePath}.table.headerBackground");
        ValidateRange(graph.Nodesep, $"{basePath}.graph.nodesep", 0.01, 10);
        ValidateRange(graph.Ranksep, $"{basePath}.graph.ranksep", 0.01, 10);
        ValidateRange(edge.PenWidth, $"{basePath}.edge.penWidth", 0.01, 10);
        ValidateRange(edge.ArrowSize, $"{basePath}.edge.arrowSize", 0.01, 10);
        ValidateIntRange(table.CellPadding, $"{basePath}.table.cellPadding", 0, 20);

        return new GraphvizDotRenderOptions(graph, node, edge, table);
    }

    private static GraphvizDotRenderOptions GetDotPreset(DiagramStyle style) =>
        style switch
        {
            DiagramStyle.Readable => new GraphvizDotRenderOptions(
                new GraphvizDotGraphRenderOptions("Helvetica", 16, 0.55, 0.9, "#FFFFFF"),
                new GraphvizDotNodeRenderOptions("Helvetica", 10),
                new GraphvizDotEdgeRenderOptions("Helvetica", 9, "#555555", 1.1, 0.7),
                new GraphvizDotTableRenderOptions("#777777", "#F1F3F5", 4)),
            DiagramStyle.Compact => new GraphvizDotRenderOptions(
                new GraphvizDotGraphRenderOptions("Arial", 14, 0.35, 0.55, "#FFFFFF"),
                new GraphvizDotNodeRenderOptions("Arial", 9),
                new GraphvizDotEdgeRenderOptions("Arial", 8, "#666666", 0.9, 0.6),
                new GraphvizDotTableRenderOptions("#8A8A8A", "#F4F4F4", 2)),
            DiagramStyle.Soft => new GraphvizDotRenderOptions(
                new GraphvizDotGraphRenderOptions("Segoe UI", 16, 0.65, 1.0, "#FBFCFA"),
                new GraphvizDotNodeRenderOptions("Segoe UI", 10),
                new GraphvizDotEdgeRenderOptions("Segoe UI", 9, "#5E7568", 1.0, 0.7),
                new GraphvizDotTableRenderOptions("#7D9488", "#EAF3EE", 5)),
            DiagramStyle.Blueprint => new GraphvizDotRenderOptions(
                new GraphvizDotGraphRenderOptions("Helvetica", 16, 0.65, 1.0, "#F7FAFC"),
                new GraphvizDotNodeRenderOptions("Helvetica", 10),
                new GraphvizDotEdgeRenderOptions("Helvetica", 9, "#2B6CB0", 1.15, 0.75),
                new GraphvizDotTableRenderOptions("#2C5282", "#EBF8FF", 5)),
            DiagramStyle.Contrast => new GraphvizDotRenderOptions(
                new GraphvizDotGraphRenderOptions("Helvetica", 17, 0.6, 0.95, "#FFFFFF"),
                new GraphvizDotNodeRenderOptions("Helvetica", 11),
                new GraphvizDotEdgeRenderOptions("Helvetica", 10, "#222222", 1.35, 0.8),
                new GraphvizDotTableRenderOptions("#333333", "#E9ECEF", 5)),
            DiagramStyle.Classic => new GraphvizDotRenderOptions(
                new GraphvizDotGraphRenderOptions(null, null, null, null, null),
                new GraphvizDotNodeRenderOptions(null, null),
                new GraphvizDotEdgeRenderOptions(null, null, null, null, null),
                new GraphvizDotTableRenderOptions(null, null, null)),
            _ => throw new ArgumentOutOfRangeException(nameof(style), style, null)
        };

    private static void ValidateColor(string? color, string path)
    {
        if (color is not null && !HexColorPattern().IsMatch(color))
        {
            throw new CliException($"{path} must be a hex color like #666666.");
        }
    }

    private static void ValidateFont(string? font, string path)
    {
        if (font is not null && !SafeFontPattern().IsMatch(font))
        {
            throw new CliException($"{path} must contain only letters, digits, spaces, '_', '-', '.', and be at most 64 characters.");
        }
    }

    private static void ValidateFontSize(int? fontSize, string path, int min, int max) =>
        ValidateIntRange(fontSize, path, min, max);

    private static void ValidateIntRange(int? value, string path, int min, int max)
    {
        if (value is not null && (value < min || value > max))
        {
            throw new CliException($"{path} must be from {min} to {max}.");
        }
    }

    private static void ValidateRange(double? value, string path, double min, double max)
    {
        if (value is not null && (value < min || value > max))
        {
            throw new CliException($"{path} must be from {min} to {max}.");
        }
    }

    private static void ValidateDiagrams(DbSketchConfig config)
    {
        if (config.Diagrams.Count == 0)
        {
            throw new CliException("diagrams must contain at least one diagram.");
        }

        ValidateCommentMaxLength(config.Defaults.Diagram.Comments.MaxLength, "defaults.diagram.comments.maxLength");

        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var diagram in config.Diagrams)
        {
            if (string.IsNullOrWhiteSpace(diagram.Name))
            {
                throw new CliException("diagrams[].name is required.");
            }

            if (!names.Add(diagram.Name.Trim()))
            {
                throw new CliException($"Duplicate diagram name '{diagram.Name}'.");
            }

            if (string.IsNullOrWhiteSpace(diagram.Output?.Path))
            {
                throw new CliException($"diagrams['{diagram.Name}'].output.path is required.");
            }
        }
    }

    private static void ValidateCommentMaxLength(int? maxLength, string path)
    {
        if (maxLength <= 0)
        {
            throw new CliException($"{path} must be greater than zero.");
        }
    }

    private static void ValidateComments(DbSketchConfig config)
    {
        var tableOverrides = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var tableOverride in config.Comments.Overrides.Tables)
        {
            if (string.IsNullOrWhiteSpace(tableOverride.Schema))
            {
                throw new CliException("comments.overrides.tables[].schema is required.");
            }

            if (string.IsNullOrWhiteSpace(tableOverride.Name))
            {
                throw new CliException("comments.overrides.tables[].name is required.");
            }

            var key = $"{tableOverride.Schema.Trim()}.{tableOverride.Name.Trim()}";
            if (!tableOverrides.Add(key))
            {
                throw new CliException($"Duplicate comment override for table '{key}'.");
            }
        }
    }

    private static void ValidateDatabase(DbSketchConfig config)
    {
        if (config.Database.CommandTimeoutSeconds is <= 0)
        {
            throw new CliException("database.commandTimeoutSeconds must be greater than zero.");
        }
    }

    private static string GetMarkdownFenceLanguage(string? configuredLanguage, DiagramFormat renderer)
    {
        if (!string.IsNullOrWhiteSpace(configuredLanguage))
        {
            return configuredLanguage;
        }

        return renderer switch
        {
            DiagramFormat.Dot => "dot",
            DiagramFormat.Mermaid => "mermaid",
            _ => throw new ArgumentOutOfRangeException(nameof(renderer), renderer, null)
        };
    }

    public static string NormalizeProvider(string? provider)
    {
        if (string.IsNullOrWhiteSpace(provider))
        {
            throw new CliException("provider is required.");
        }

        return provider.Trim().ToLowerInvariant() switch
        {
            "mssql" => "sqlserver",
            "sqlserver" => "sqlserver",
            "postgresql" => "postgres",
            "postgres" => "postgres",
            "mysql" => "mysql",
            var value => throw new CliException($"Unknown provider '{value}'. Supported values: sqlserver, postgres, mysql.")
        };
    }

    [GeneratedRegex("^#[0-9A-Fa-f]{6}$")]
    private static partial Regex HexColorPattern();

    [GeneratedRegex("^[A-Za-z0-9 _\\-.]{1,64}$")]
    private static partial Regex SafeFontPattern();
}
