using DimonSmart.DbSketch.Core.Config;
using DimonSmart.DbSketch.Core.Rendering;
using DimonSmart.DbSketch.Core.Schema;

namespace DimonSmart.DbSketch.Cli;

public sealed record ResolvedGenerateOptions(
    string Provider,
    string ConnectionString,
    bool Verbose,
    bool Quiet,
    bool NoProgress,
    bool DryRun,
    bool ReadComments,
    int? CommandTimeoutSeconds,
    CommentOverridesConfig CommentOverrides,
    IReadOnlyList<ResolvedDiagramTarget> Diagrams);

public sealed record ResolvedDiagramTarget(
    string Name,
    string OutputPath,
    DiagramFormat DiagramRenderer,
    OutputFormat Output,
    SchemaFilterOptions Filter,
    DiagramRenderOptions Diagram);

public static class GenerateOptionsResolver
{
    public static ResolvedGenerateOptions Resolve(DbSketchConfig config, CliOptions cli)
    {
        if (string.IsNullOrWhiteSpace(cli.ConfigPath))
        {
            throw new CliException("--config is required.");
        }

        var provider = NormalizeProvider(config.Provider);
        if (string.IsNullOrWhiteSpace(config.ConnectionString))
        {
            throw new CliException("connectionString is required.");
        }

        ValidateDatabase(config);
        ValidateComments(config);
        ValidateDiagrams(config);

        var diagrams = ResolveDiagrams(config, cli.DiagramName);

        return new ResolvedGenerateOptions(
            provider,
            config.ConnectionString,
            cli.Verbose,
            cli.Quiet,
            cli.NoProgress,
            cli.DryRun,
            config.Comments.Enabled,
            config.Database.CommandTimeoutSeconds,
            config.Comments.Overrides,
            diagrams);
    }

    private static IReadOnlyList<ResolvedDiagramTarget> ResolveDiagrams(DbSketchConfig config, string? selectedDiagramName)
    {
        var sourceDiagrams = config.Diagrams;
        if (!string.IsNullOrWhiteSpace(selectedDiagramName))
        {
            var selected = sourceDiagrams.FirstOrDefault(diagram => string.Equals(diagram.Name, selectedDiagramName, StringComparison.OrdinalIgnoreCase));
            if (selected is null)
            {
                throw new CliException($"Diagram '{selectedDiagramName}' was not found. Available diagrams: {string.Join(", ", sourceDiagrams.Select(diagram => diagram.Name))}.");
            }

            sourceDiagrams = [selected];
        }

        return sourceDiagrams.Select(diagram => ResolveDiagram(config.Defaults, diagram)).ToArray();
    }

    private static ResolvedDiagramTarget ResolveDiagram(DefaultsConfig defaults, DiagramTargetConfig target)
    {
        var diagramRenderer = DiagramRendererParser.Parse(target.Diagram?.Renderer ?? defaults.Diagram.Renderer);
        var outputFormat = OutputContainerFormatParser.Parse(target.Output?.Format ?? defaults.Output.Format);
        var direction = DiagramDirectionParser.Parse(target.Diagram?.Direction ?? defaults.Diagram.Direction);
        var title = string.IsNullOrWhiteSpace(target.Title)
            ? defaults.Diagram.Title ?? "Database schema"
            : target.Title;

        var commentMaxLength = target.Diagram?.Comments?.MaxLength ?? defaults.Diagram.Comments.MaxLength;
        ValidateCommentMaxLength(commentMaxLength, $"diagrams['{target.Name}'].diagram.comments.maxLength");

        var markdownOptions = outputFormat == OutputContainerFormat.Markdown
            ? new MarkdownRenderOptions(
                GetMarkdownFenceLanguage(target.Output?.Markdown?.FenceLanguage ?? defaults.Output.Markdown.FenceLanguage, diagramRenderer),
                target.Output?.Markdown?.Header ?? defaults.Output.Markdown.Header ?? $"# {title}{Environment.NewLine}{Environment.NewLine}Generated by DbSketch.",
                target.Output?.Markdown?.Footer ?? defaults.Output.Markdown.Footer)
            : null;

        return new ResolvedDiagramTarget(
            target.Name!,
            target.Output!.Path!,
            diagramRenderer,
            new OutputFormat(outputFormat, markdownOptions),
            new SchemaFilterOptions(target.Include.Tables, target.Exclude.Tables),
            new DiagramRenderOptions(
                title,
                direction,
                target.Diagram?.Compact ?? defaults.Diagram.Compact,
                ResolveShowOptions(defaults.Diagram.Show, target.Diagram?.Show),
                new MermaidRenderOptions(target.Diagram?.Mermaid?.EmitDirection ?? defaults.Diagram.Mermaid.EmitDirection),
                new DiagramCommentRenderOptions(commentMaxLength)));
    }

    private static DiagramShowOptions ResolveShowOptions(DiagramShowConfig defaults, DiagramShowOverrideConfig? overrides) =>
        new(
            overrides?.SchemaName ?? defaults.SchemaName,
            overrides?.ColumnTypes ?? defaults.ColumnTypes,
            overrides?.Nullability ?? defaults.Nullability,
            overrides?.PrimaryKeys ?? defaults.PrimaryKeys,
            overrides?.ForeignKeys ?? defaults.ForeignKeys,
            overrides?.ForeignKeyLabels ?? defaults.ForeignKeyLabels,
            overrides?.SelfReferencingForeignKeys ?? defaults.SelfReferencingForeignKeys,
            overrides?.TableComments ?? defaults.TableComments,
            overrides?.ColumnComments ?? defaults.ColumnComments);

    private static void ValidateDiagrams(DbSketchConfig config)
    {
        if (config.Diagrams.Count == 0)
        {
            throw new CliException("diagrams must contain at least one diagram.");
        }

        ValidateCommentMaxLength(config.Defaults.Diagram.Comments.MaxLength, "defaults.diagram.comments.maxLength");

        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var diagram in config.Diagrams)
        {
            if (string.IsNullOrWhiteSpace(diagram.Name))
            {
                throw new CliException("diagrams[].name is required.");
            }

            if (!names.Add(diagram.Name.Trim()))
            {
                throw new CliException($"Duplicate diagram name '{diagram.Name}'.");
            }

            if (string.IsNullOrWhiteSpace(diagram.Output?.Path))
            {
                throw new CliException($"diagrams['{diagram.Name}'].output.path is required.");
            }
        }
    }

    private static void ValidateCommentMaxLength(int? maxLength, string path)
    {
        if (maxLength <= 0)
        {
            throw new CliException($"{path} must be greater than zero.");
        }
    }

    private static void ValidateComments(DbSketchConfig config)
    {
        var tableOverrides = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var tableOverride in config.Comments.Overrides.Tables)
        {
            if (string.IsNullOrWhiteSpace(tableOverride.Schema))
            {
                throw new CliException("comments.overrides.tables[].schema is required.");
            }

            if (string.IsNullOrWhiteSpace(tableOverride.Name))
            {
                throw new CliException("comments.overrides.tables[].name is required.");
            }

            var key = $"{tableOverride.Schema.Trim()}.{tableOverride.Name.Trim()}";
            if (!tableOverrides.Add(key))
            {
                throw new CliException($"Duplicate comment override for table '{key}'.");
            }
        }
    }

    private static void ValidateDatabase(DbSketchConfig config)
    {
        if (config.Database.CommandTimeoutSeconds is <= 0)
        {
            throw new CliException("database.commandTimeoutSeconds must be greater than zero.");
        }
    }

    private static string GetMarkdownFenceLanguage(string? configuredLanguage, DiagramFormat renderer)
    {
        if (!string.IsNullOrWhiteSpace(configuredLanguage))
        {
            return configuredLanguage;
        }

        return renderer switch
        {
            DiagramFormat.Dot => "dot",
            DiagramFormat.Mermaid => "mermaid",
            _ => throw new ArgumentOutOfRangeException(nameof(renderer), renderer, null)
        };
    }

    public static string NormalizeProvider(string? provider)
    {
        if (string.IsNullOrWhiteSpace(provider))
        {
            throw new CliException("provider is required.");
        }

        return provider.Trim().ToLowerInvariant() switch
        {
            "mssql" => "sqlserver",
            "sqlserver" => "sqlserver",
            "postgresql" => "postgres",
            "postgres" => "postgres",
            "mysql" => "mysql",
            var value => throw new CliException($"Unknown provider '{value}'. Supported values: sqlserver, postgres, mysql.")
        };
    }
}
