using DimonSmart.DbSketch.Core.Rendering;

namespace DimonSmart.DbSketch.Tests;

public sealed class MarkdownDiagramWrapperTests
{
    [Fact]
    public void WrapsDotDiagram()
    {
        var markdown = MarkdownDiagramWrapper.Wrap("digraph DbSketch {\n}\n", DiagramFormat.Dot, "Database schema");

        Assert.Contains("# Database schema", markdown);
        Assert.Contains("Generated by DbSketch.", markdown);
        Assert.Contains("```dot", markdown);
        Assert.Contains("digraph DbSketch {\n}\n```", markdown);
    }

    [Fact]
    public void WrapsMermaidDiagram()
    {
        var diagram = "erDiagram\n  direction LR\n";

        var markdown = MarkdownDiagramWrapper.Wrap(diagram, DiagramFormat.Mermaid, "Database schema");

        Assert.Contains("```mermaid", markdown);
        Assert.Contains($"{diagram}```", markdown);
    }
}
