using DimonSmart.DbSketch.Core.Rendering;

namespace DimonSmart.DbSketch.Tests;

public sealed class MarkdownDiagramWrapperTests
{
    [Fact]
    public void WrapsDotDiagramWithDotFence()
    {
        var markdown = MarkdownDiagramWrapper.Wrap(
            "digraph DbSketch {\n}\n",
            new MarkdownRenderOptions("dot", "# Database schema\n\nGenerated by DbSketch.", null));

        Assert.Contains("# Database schema", markdown);
        Assert.Contains("Generated by DbSketch.", markdown);
        Assert.Contains("```dot", markdown);
        Assert.Contains("digraph DbSketch {\n}\n```", markdown);
    }

    [Fact]
    public void WrapsDotDiagramWithGraphvizFence()
    {
        var markdown = MarkdownDiagramWrapper.Wrap(
            "digraph DbSketch {\n}\n",
            new MarkdownRenderOptions("graphviz", "# Database schema\n\nGenerated by DbSketch.", null));

        Assert.Contains("# Database schema", markdown);
        Assert.Contains("Generated by DbSketch.", markdown);
        Assert.Contains("```graphviz", markdown);
        Assert.Contains("digraph DbSketch {\n}\n```", markdown);
    }

    [Fact]
    public void WrapsMermaidDiagramWithMermaidFence()
    {
        var diagram = "erDiagram\n  direction LR\n";

        var markdown = MarkdownDiagramWrapper.Wrap(
            diagram,
            new MarkdownRenderOptions("mermaid", "# Database schema\n\nGenerated by DbSketch.", null));

        Assert.Contains("```mermaid", markdown);
        Assert.Contains($"{diagram}```", markdown);
    }

    [Fact]
    public void WrapsMarkdownWithCustomHeaderAndFooter()
    {
        var markdown = MarkdownDiagramWrapper.Wrap(
            "erDiagram\n",
            new MarkdownRenderOptions(
                "mermaid",
                "# Custom header\n\nSome text.",
                "---\nCustom footer."));

        Assert.StartsWith("# Custom header", markdown);
        Assert.Contains("Some text.", markdown);
        Assert.Contains("```mermaid", markdown);
        Assert.Contains("erDiagram", markdown);
        Assert.Contains("---", markdown);
        Assert.Contains("Custom footer.", markdown);
    }

    [Fact]
    public void WrapsMarkdownWithoutHeaderWhenHeaderIsEmpty()
    {
        var markdown = MarkdownDiagramWrapper.Wrap(
            "erDiagram\n",
            new MarkdownRenderOptions("mermaid", "", null));

        Assert.StartsWith("```mermaid", markdown);
        Assert.DoesNotContain("Generated by DbSketch.", markdown);
    }

    [Fact]
    public void WrapsMarkdownWithoutFooterWhenFooterIsEmpty()
    {
        var markdown = MarkdownDiagramWrapper.Wrap(
            "erDiagram\n",
            new MarkdownRenderOptions("mermaid", "# Header", ""));

        Assert.DoesNotContain("---", markdown);
    }

    [Fact]
    public void ThrowsForEmptyFenceLanguage()
    {
        var exception = Assert.Throws<ArgumentException>(() => MarkdownDiagramWrapper.Wrap(
            "digraph DbSketch {\n}\n",
            new MarkdownRenderOptions(" ", "# Database schema", null)));

        Assert.Equal("fenceLanguage", exception.ParamName);
    }
}
