using DimonSmart.DbSketch.Core.Rendering;

namespace DimonSmart.DbSketch.Tests;

public sealed class MarkdownDiagramWrapperTests
{
    [Fact]
    public void WrapsDotDiagramWithDotFence()
    {
        var markdown = MarkdownDiagramWrapper.Wrap("digraph DbSketch {\n}\n", "dot", "Database schema");

        Assert.Contains("# Database schema", markdown);
        Assert.Contains("Generated by DbSketch.", markdown);
        Assert.Contains("```dot", markdown);
        Assert.Contains("digraph DbSketch {\n}\n```", markdown);
    }

    [Fact]
    public void WrapsDotDiagramWithGraphvizFence()
    {
        var markdown = MarkdownDiagramWrapper.Wrap("digraph DbSketch {\n}\n", "graphviz", "Database schema");

        Assert.Contains("# Database schema", markdown);
        Assert.Contains("Generated by DbSketch.", markdown);
        Assert.Contains("```graphviz", markdown);
        Assert.Contains("digraph DbSketch {\n}\n```", markdown);
    }

    [Fact]
    public void WrapsMermaidDiagramWithMermaidFence()
    {
        var diagram = "erDiagram\n  direction LR\n";

        var markdown = MarkdownDiagramWrapper.Wrap(diagram, "mermaid", "Database schema");

        Assert.Contains("```mermaid", markdown);
        Assert.Contains($"{diagram}```", markdown);
    }

    [Fact]
    public void ThrowsForEmptyFenceLanguage()
    {
        var exception = Assert.Throws<ArgumentException>(() => MarkdownDiagramWrapper.Wrap("digraph DbSketch {\n}\n", " ", "Database schema"));

        Assert.Equal("fenceLanguage", exception.ParamName);
    }
}
